#!/bin/bash

if [ -d "./lib" ];then
    mkdir include;
    mkdir src;
    ln -s ../lib/include/libmy.h include/libmy.h;
    ln -s ../lib/include/macro.h include/macro.h;
    ln -s ../lib/include/depend.mk include/depend.mk;
    ln -s lib/tools ./tools;
else
    echo "Vous n'etes pas à la racine ou pas de lib."
fi
