#!/bin/bash

if [ -d "./lib" ];then
    mkdir include;
    mkdir src;
    ln -s ../lib/my/include/libmy.h include/libmy.h;
    ln -s ../lib/my/include/depend.mk include/depend.mk;
    ln -s ./lib/my/tools ./tools;
else
    echo "Pas dans le bon dossier"
fi
